spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  thymeleaf:
    encoding: UTF-8
    enabled: true
    suffix: .html
#spring:
#  datasource:
#    url: jdbc:h2:~/data/cagong
#  jpa:
#    hibernate:
#      ddl-auto: update

#jwt:
#  secret: 12345678901234567890123456789012
---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true