language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r cagong-ranking-project *
  - mkdir -p deploy
  - mv cagong-ranking-project.zip deploy/cagong-ranking-project.zip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: springboot-build-and-img # bucket name
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy # before_deploy에서 생성한 디렉토리
  wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'joybeanie@gmail.com'