spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cafe
    username: root
    password: gks82465512
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  datasource:
#    url: jdbc:h2:~/data/cagong
#  jpa:
#    hibernate:
#      ddl-auto: update

#jwt:
#  secret: 12345678901234567890123456789012
---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

---